### ISSUE TITLE
UE4.23 port to ppc64el

### ISSUE THREAD

**Issue by ticlazau** [edowson/raptor-talos-ii-power9-technote#1]
Hi @edowson 

Did you manage to get UE4.23 port to ppc64el?

Rgds,

**Comment by edowson** [comment]
@ticlazau 

UE4.22.3 is currently a work in progress, it might take another week or two before I get `UE4Editor` running on `ppc64le`. You can find the current progress in the [4.22-ppc64le](https://github.com/edowson/UnrealEngine/commits/4.22-ppc64le) branch.

I'll work on the UE4.23.0 port after I've got UE4.22.3 up and running.

I'm also porting those patches to the UE4 master branch at the same time. I'll split the effort into two parts, one for general script fixes, and the other for ppc64le enablement for master branch.

https://github.com/EpicGames/UnrealEngine/pull/6157

**Comment by ticlazau** [comment]
Thank you @edowson I am interested to get UE running on AC922 for CARLA simulator.
Looking forward.

Rgds,
FM

**Comment by ticlazau** [comment]
Hi, @edowson any progress on porting UE4.22.3 on ppc64le? I have seen that the related git is not active anymore.

Rgds,
FM

**Comment by edowson** [comment]
I'm working on the [master-ppc64le](https://github.com/edowson/UnrealEngine/commits/master-ppc64le) branch, at the moment.

There are some more libraries that I need to finish porting to power9, before it can run.

**Comment by ticlazau** [comment]
Thanks, @edowson looking forward :)

**Comment by edowson** [comment]
@ticlazau There is currently too much churn in 4.24 / master branch, as support for Aarch64 is being added. I'll wait until 4.24 stabilizes before resuming work on the master branch.

I'm working on the [4.23-ppc64le](https://github.com/edowson/UnrealEngine/commits/4.23-ppc64le) branch at the moment. 

Here is a list of remaining third-party libraries that need to be re-built / ported for ppc64le:
- [x] PhysX3
- [ ] WebRTC
- [x] MikkTSpace
- [ ] CEF3
- [x] VHACD
- [x] Kiss_FFT
- [x] SpeedTree
- [ ] OpenEXR
- [ ] Python for ppc64le

**Comment by edowson** [comment]
An initial port of UE4.23.1 for ppc64le can be found here:
https://github.com/edowson/UnrealEngine/tree/4.23-ppc64le

I used the First Person blueprint as a test project. 

Since I'm accessing my Talos 2 system remotely using VirtualGL and TurboVNC, my frame rate is very low.

VirtualGL currently has no support for `VirtualVulkan` rendering.

So, I had to reintroduce legacy OpenGL support into UE4.32.1 for preliminary testing on ppc64le using remote desktop access. The combination of VirtualGL and TurboVNC only support OpenGL3.1 and a GPU SM4 emulation, even if you have the latest RTX GPUs with SM75 capabilities and NVIDIA proprietary drivers installed.

The command I used to launch editor for remote desktop access is: 
```
Engine/Binaries/Linux/UE4Editor -opengl3
```

However, the UE4Editor requires proper GPU support with SM5 capabilities, and preferably vulkan or opengl4.
```
Engine/Binaries/Linux/UE4Editor -vulkan
Engine/Binaries/Linux/UE4Editor -opengl4
```

To enable vulkan, change this line to `DynamicallyLoadedModuleNames.Add("VulkanRHI");`

https://github.com/edowson/UnrealEngine/blob/4.23-ppc64le/Engine/Source/Runtime/RHI/RHI.Build.cs#L43

New project window:
![201911231557-ue4 23-new-project-window](https://user-images.githubusercontent.com/10365427/69478594-caeb3f80-0e0d-11ea-8596-4fb7f0d3c43e.png)

FPS game play in editor window:
![201911231607-ue4 23-fps-game-01](https://user-images.githubusercontent.com/10365427/69478602-d6d70180-0e0d-11ea-9d12-03f56256beca.png)

Ref:
- https://github.com/carla-simulator/carla/issues/1567
- https://github.com/EpicGames/UnrealEngine/pull/2585
- https://github.com/EpicGames/UnrealEngine/pull/6157
- https://github.com/VirtualGL/virtualgl/issues/37

**Comment by ticlazau** [comment]
@edowson  I can't access your repo: 
https://github.com/edowson/UnrealEngine/tree/4.23-ppc64le
Can you give me access to it?

Rgds,
FM

**Comment by edowson** [comment]
You need to sign up with Epic’s EULA on github. Once you’ve done that, your access to my fork of Epic’s repo will be automatic.

**Comment by runlevel5** [comment]
@edowson It's a pity that EpicGames decided not to support OpenPOWER platform. I guess the community can continue maintaining a separate fork for the time-being. Wondering if you could re-base your `4.23-ppc64le` against upstream's `master`?

**Comment by edowson** [comment]
@runlevel5 Epic has made several improvements to the way new platforms are supported since `4.24` . It will be a significant effort to add support for `4.25-ppc64le`. I won't do it against current `master` since it is a moving target with significant code churn.

**Comment by benjha** [comment]
@piprrr 
This may be of interest.

**Comment by markcoletti** [comment]
Indeed, we have a fellow here, Quentin Haas, that has been following @edowson closely to port UE to run on Summit.  Truly he's done yeoman's work there because that has been a difficult process fraught with challenges.

**Comment by edowson** [comment]
@piprrr I'm looking at adding support for `4.25-ppc64le` so that that will give a newer baseline for the various UE4-based simulation plugins.
